version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building app..."
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar