version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building using Maven Wrapper..."
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - target/*.jar