version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - export JAVA_HOME=$JAVA_17_HOME
      - export PATH=$JAVA_HOME/bin:$PATH
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - target/*.jar